version: '3'
services:
  backend:
    image: docker.io/library/backend:0.0.1-SNAPSHOT
    container_name: backend
    ports:
      - 8080:8080
    environment:
      DB_USER: root
      DB_PASSWORD: hoodydb
      DB_HOST: 172.17.0.1:3306
