spring:
  datasource:
    host: ${DB_HOST}
    url: jdbc:mysql://${spring.datasource.host}/${DB_NAME:blog}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
